 CREATE TABLE "APP_INFO" 
   (	"ID" NUMBER, 
	"APP_NO" VARCHAR2(400), 
	"APPLICATION_TYPE" VARCHAR2(400), 
	"FUNCTIONAL_OWNER" VARCHAR2(4000), 
	"FUNCTIONAL_AREA" VARCHAR2(4000), 
	"APP_DEV_TEAM" VARCHAR2(400), 
	"FUNCTION_NAME" VARCHAR2(4000), 
	"PROCESS_NAME" VARCHAR2(4000), 
	"PROCESS_DESCRIPTION" VARCHAR2(4000), 
	"WORKSPACE_NAME" VARCHAR2(400), 
	"DB_SCHEMA" VARCHAR2(400), 
	"TECHNOLOGY" VARCHAR2(1000), 
	"SERVER_ID" VARCHAR2(4000), 
	"DEV_LINK" VARCHAR2(4000), 
	"SIT_LINK" VARCHAR2(4000), 
	"DEV_LIT_LINK" VARCHAR2(4000), 
	"SIT_LIT_LINK" VARCHAR2(4000), 
	"PROD_LINK" VARCHAR2(4000), 
	"CRITICALITY" VARCHAR2(400), 
	"DEVELOPER_SME_PRIMARY1" VARCHAR2(400), 
	"DEVELOPER_SME_PRIMARY2" VARCHAR2(400), 
	"DEVELOPER_SME_SECONDARY1" VARCHAR2(400), 
	"DEVELOPER_SME_SECONDARY2" VARCHAR2(400), 
	"BUSINESS_CONTACTS" VARCHAR2(4000), 
	"APPLICATION_CREATED_ON" DATE, 
	"APPLICATION_LAST_UPDATED" DATE, 
	"NOTE" VARCHAR2(4000), 
	"UPSTREAM" VARCHAR2(4000), 
	"DOWNSTREAM" VARCHAR2(4000), 
	"DEPENDENCIES" VARCHAR2(4000), 
	"SVN_LINK" VARCHAR2(400), 
	"OUD_GROUPS" VARCHAR2(4000), 
	"CREATED_ON" DATE, 
	"CREATED_BY" VARCHAR2(400), 
	"UPDATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(400), 
	 CONSTRAINT "APP_INFO_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_APP_INFO" 
before insert or update
    on APP_INFO
   for each row
declare
  -- local variables here

begin
  --CHECK_VAL := 11;-- for test
  if INSERTING then
    :new.ID := APP_INFO_SEQ.nextval;
    :new.CREATED_ON := SYSDATE;

    select nvl(v('APP_USER'),'WKSP_VIJAYAVINAY')
    into :new.CREATED_BY
    from dual;

    :new.UPDATED_ON := SYSDATE;
    :new.UPDATED_BY := :new.CREATED_BY;
  end if;
  if UPDATING then
    :new.UPDATED_ON := SYSDATE;

    select nvl(v('APP_USER'),'WKSP_VIJAYAVINAY')
    into :new.UPDATED_BY
    from dual;
  end if;
end BIU_APP_INFO_SEQ;
/
ALTER TRIGGER "BIU_APP_INFO" ENABLE;
/

CREATE SEQUENCE  "APP_INFO_SEQ"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 82 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
/

  CREATE TABLE "SERVER_LIST" 
   (	"ID" NUMBER, 
	"SERVER_NAME" VARCHAR2(200 CHAR), 
	"SERVER_IP" VARCHAR2(200 CHAR), 
	"SERVER_TYPE" VARCHAR2(200 CHAR), 
	"DB_SERVER" VARCHAR2(200 CHAR), 
	 CONSTRAINT "PK_ID" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
   /